export const POSTS = [
  {slug:'임플란트-주위염-초기증상-자가진단법',keyword:'임플란트 주위염 초기 증상 자가 진단법',situation:'임플란트 식립 후 잇몸 출혈·부종이 나타나는 환자',angle:'자각 증상이 없는 임플란트 주위염의 조기 발견 핵심 체크리스트',category:'임플란트 관리',imageQuery:'dental implant checkup'},
  {slug:'당뇨환자-임플란트-수술전-체크리스트',keyword:'당뇨 환자 임플란트 수술 전 필수 체크리스트',situation:'혈당 조절 중인 50~60대 당뇨 환자',angle:'HbA1c 수치별 수술 가능 기준과 내과 협진 포인트',category:'수술 전 준비',imageQuery:'blood sugar test diabetes'},
  {slug:'어금니-임플란트-뼈이식-통증-대처법',keyword:'어금니 임플란트 뼈이식 후 통증 2주 넘게 지속 대처법',situation:'뼈이식 동반 임플란트 수술 후 회복이 더딘 환자',angle:'정상 회복 과정 vs 이상 신호 구분법과 응급 내원 기준',category:'수술 후 관리',imageQuery:'dental xray molar'},
  {slug:'임플란트-흡연자-실패율-금연기간',keyword:'임플란트 흡연자 실패율 금연 기간 가이드',situation:'흡연 중이면서 임플란트를 고려하는 30~50대 남성',angle:'흡연이 골유착에 미치는 영향과 최소 금연 기간 근거',category:'수술 전 준비',imageQuery:'quit smoking health'},
  {slug:'60대-임플란트-틀니-비용-비교',keyword:'60대 전체 임플란트 vs 틀니 비용 수명 비교',situation:'다수 치아 상실로 전악 재건을 고민하는 60대',angle:'올온포 임플란트와 총의치의 10년 비용 대비 효과 분석',category:'비용·보험',imageQuery:'senior dental care'},
  {slug:'임플란트-수술후-음식-식단가이드',keyword:'임플란트 수술 후 음식 언제부터 먹어도 되나요',situation:'임플란트 식립 직후 식사가 걱정되는 환자',angle:'수술 당일부터 완전 회복까지 주차별 식단 가이드',category:'수술 후 관리',imageQuery:'soft food diet'},
  {slug:'앞니-임플란트-심미성-자연치아',keyword:'앞니 임플란트 심미성 자연치아처럼 보이는 방법',situation:'앞니 상실로 외모 콤플렉스를 느끼는 20~40대',angle:'잇몸 라인 성형과 맞춤형 지르코니아 보철의 심미 전략',category:'심미 치료',imageQuery:'beautiful smile teeth'},
  {slug:'임플란트-나사풀림-증상-응급대처',keyword:'임플란트 나사 풀림 증상 원인 응급 대처법',situation:'보철물이 흔들리거나 느슨해진 느낌을 받는 환자',angle:'나사 풀림 vs 골유착 파괴 구분법과 즉시 대응 방법',category:'응급 상황',imageQuery:'dental implant model'},
  {slug:'골다공증-약-임플란트-가능여부',keyword:'골다공증 약 복용 중 임플란트 가능한가요',situation:'비스포스포네이트 계열 약물 복용 중인 고령 여성',angle:'약물 휴지기 필요 여부와 악골괴사 위험 최소화 전략',category:'전신질환',imageQuery:'medicine pills prescription'},
  {slug:'임플란트-음식물끼임-치간칫솔-워터픽',keyword:'임플란트 음식물 끼임 해결 치간칫솔 워터픽 사용법',situation:'임플란트와 자연치아 사이 음식물이 계속 끼는 환자',angle:'보철물 형태별 맞춤 구강 관리 도구 선택과 사용 테크닉',category:'임플란트 관리',imageQuery:'interdental brush oral care'},
  {slug:'임플란트-수명-10년-20년-관리비결',keyword:'임플란트 수명 10년 20년 오래 쓰는 관리 비결',situation:'이미 임플란트를 한 상태에서 장기 유지가 걱정인 환자',angle:'논문 기반 임플란트 장기 생존율과 리콜 주기 가이드',category:'임플란트 관리',imageQuery:'dental checkup patient'},
  {slug:'상악동거상술-부작용-축농증-예방',keyword:'상악동 거상술 부작용 축농증 위험 예방법',situation:'위쪽 어금니 뼈가 부족해 상악동 수술이 필요한 환자',angle:'상악동 천공 위험과 수술 후 축농증 예방을 위한 핵심 관리',category:'수술 정보',imageQuery:'dental surgery'},
  {slug:'임플란트-MRI-촬영-안전성',keyword:'임플란트 MRI 촬영 가능한가요 자기공명영상 안전성',situation:'건강검진 MRI를 앞두고 임플란트 때문에 걱정하는 환자',angle:'티타늄 임플란트의 자성 반응과 MRI 촬영 시 실제 주의사항',category:'자주 묻는 질문',imageQuery:'MRI scan hospital'},
  {slug:'즉시-임플란트-당일식립-장단점',keyword:'즉시 임플란트 당일 식립 장단점 적합한 경우',situation:'발치 후 바로 임플란트를 심고 싶은 환자',angle:'즉시 식립의 성공 조건과 지연 식립이 더 나은 케이스 구분',category:'수술 정보',imageQuery:'dentist patient consultation'},
];
export function getPostBySlug(s){return POSTS.find(p=>p.slug===s)||null}
export function getAllSlugs(){return POSTS.map(p=>p.slug)}
export function getCategories(){const c={};POSTS.forEach(p=>{if(!c[p.category])c[p.category]=[];c[p.category].push(p)});return c}
export function buildArticleHTML(post,imgUrl){const{keyword:k,situation:s,angle:a}=post;return`<p>${s}에 해당하시나요? 이 글은 바로 그런 분들을 위해 준비했습니다. ${a}에 대해, 최신 연구 논문과 학회 가이드라인을 근거로 상세히 안내해 드리겠습니다.</p>${imgUrl?`<img src="${imgUrl}" alt="${k} 관련 치과 진료 안내 이미지" style="width:100%;border-radius:12px;margin:20px 0"/>`:''}<h2>문제의 원인과 현황</h2><p>최근 한국소비자원 통계에 따르면, 국내 임플란트 시술 건수는 2021년 약 55만 건에서 2023년 약 61만 건으로 꾸준히 증가하고 있습니다.</p><p>Galarraga-Vinueza 등이 2025년 <em>Journal of Periodontology</em>에 발표한 AO/AAP 체계적 문헌고찰에 따르면, 임플란트 주위점막염의 환자 수준 유병률은 약 46%, 임플란트 주위염은 약 21%로 보고되었습니다.</p><p>특히 <strong>"${k}"</strong>와 관련하여, ${s}의 경우에는 더욱 세심한 주의가 필요합니다.</p><h2>논문 기반의 해결책 및 치료 가이드</h2><p>대한치주과학회가 2025년 발표한 임플란트 주위질환 진단 및 치료 가이드라인(2025 KAP Consensus)에서는 단계별 알고리즘을 체계적으로 제시하고 있습니다.</p><ul><li><strong>조기 발견이 핵심:</strong> 임플란트에는 치주인대가 없어 자각 증상이 거의 없습니다. 정기 검진이 유일한 조기 발견 방법입니다.</li><li><strong>단계별 치료:</strong> 초기 점막염은 스케일링으로 회복 가능. 골 소실 동반 시 외과적 치료가 필요할 수 있습니다.</li><li><strong>위험인자 관리:</strong> 치주염 병력(OR 3.84)과 흡연(RR 2.07)이 가장 강력한 위험 인자입니다.</li></ul><h2>환자가 집에서 할 수 있는 관리 팁</h2><p><strong>1. 칫솔질법 익히기</strong> — 45도 각도로 잇몸 경계를 부드럽게 닦으세요.</p><p><strong>2. 치간칫솔·워터픽 사용</strong> — 매 식후 보조 도구를 함께 사용하세요.</p><p><strong>3. 6개월마다 정기 검진</strong> — 방사선 촬영과 탐침 검사를 받으세요.</p><p><strong>4. 금연 실천</strong> — 흡연자의 주위염 발생률은 비흡연자의 약 3배입니다.</p><p><strong>5. 전신 질환 관리</strong> — 당뇨 등 기저질환을 철저히 관리하세요.</p><h2>마무리</h2><p>임플란트는 잘 관리하면 10년 이상 사용할 수 있습니다. 매일의 구강 관리와 정기 치과 방문을 꼭 기억해 주세요.</p><p><strong>⚠ 본 글은 논문 기반 일반 건강 정보이며, 전문의 진료를 대신하지 않습니다.</strong></p>`}
export function buildFaqSchema(){return JSON.stringify({"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"임플란트 주위염은 얼마나 흔한가요?","acceptedAnswer":{"@type":"Answer","text":"환자의 약 21%에서 발생합니다."}},{"@type":"Question","name":"초기 증상은?","acceptedAnswer":{"@type":"Answer","text":"칫솔질 시 잇몸 출혈, 부종, 발적, 입냄새 악화 등이 나타납니다."}},{"@type":"Question","name":"흡연자는 더 취약한가요?","acceptedAnswer":{"@type":"Answer","text":"네. 비흡연자 대비 약 2배 이상 위험합니다."}}]})}